spec:
  template:
    spec:
      serviceAccountName: ${project.artifactId}-sa
      containers:
      - name: ${project.artifactId}
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/etc/config/
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: spring.datasource.password
        - name: AMQPHUB_AMQP10JMS_USERNAME
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: amqphub.amqp10jms.username
        - name: AMQPHUB_AMQP10JMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: amqphub.amqp10jms.password
        - name: APP_RULES_CLIENT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: app.rules-client.username
        - name: APP_RULES_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${project.artifactId}-secret
              key: app.rules-client.password
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "4.0"
        volumeMounts:
        - name: ${project.artifactId}-configmap-vol
          mountPath: /etc/config
          readOnly: true
        - name: rawfiles-vol
          mountPath: /mnt
      volumes:
      - name: ${project.artifactId}-configmap-vol
        configMap:
          name: ${project.artifactId}-configmap
      - name: rawfiles-vol
        persistentVolumeClaim:
          claimName: rawfiles
