CREATE TABLE example.SCORED_DATA_RESULTS_AGGREGATION (
 id VARCHAR(255) NOT NULL,
 exchange BLOB NOT NULL,
 CONSTRAINT SCORED_DATA_RESULTS_AGGREGATION_pk PRIMARY KEY (id) 
);
 
CREATE TABLE example.SCORED_DATA_RESULTS_AGGREGATION_completed (
 id VARCHAR(255) NOT NULL,
 exchange BLOB NOT NULL,
 CONSTRAINT SCORED_DATA_RESULTS_AGGREGATION_completed_pk PRIMARY KEY (id) 
);